# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QssEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5.QtGui import QKeySequence
from PyQt5.QtWidgets import QApplication, QMainWindow, QShortcut
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal,QPoint
from PyQt5.QtWidgets import QPushButton,QFrame,QWidget,QGridLayout,QLineEdit,QSpinBox,QLabel

from GuiLib import QSSEdit
from core.controlShell import ControlShell,ControlGroup

class QssEdit(QMainWindow):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)

        # 控件组
        self.__control_group = ControlGroup()

        # 控件字典
        self.__control_dict = dict()

        self.setupUi()

        self.myEvent()

    # 切换控件
    def controlSwitch(self,cname:tuple):
        print("controlSwitch",cname)
        c_name,name = cname

    def setupUi(self):
        self.setObjectName("self")
        self.resize(1121, 748)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.code_edit = QSSEdit(self.centralwidget)
        self.code_edit.setMinimumSize(QtCore.QSize(521, 0))
        self.code_edit.setObjectName("code_edit")
        self.horizontalLayout.addWidget(self.code_edit)


        self.preview = QtWidgets.QStackedWidget(self.centralwidget)
        self.preview.setObjectName("preview")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")

        # ---------------
        self.ss = ControlShell("QPushButton","btn",self.page)
        self.ss.setGeometry(90, 90, 120, 80)
        self.ss.activate(True)
        self.__control_group.addControlShell(self.ss)
        self.__control_group.setActivateControl(*self.ss.name())


        self.pp = ControlShell("QPushButton","btn2",self.page)
        self.pp.activate(True)
        self.__control_group.addControlShell(self.pp)
        self.__control_group.setActivateControl(*self.pp.name())
        #-----------------

        self.preview.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.preview.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.preview)
        self.setCentralWidget(self.centralwidget)


        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 23))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)

        # 状态栏
        self.myStatusbar()

        self.preview.setCurrentIndex(0)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def w_Event(self,w):
        w = int(w)
        obj = self.__control_group.getActivateControl().getObj()
        obj.resize(w,obj.height())
        obj.setMinimumSize(w,obj.height())
        win = self.__control_group.getActivateControl().getSelf()
        win.resize(w+1,win.height())


    def h_Event(self,h):
        h = int(h)
        obj = self.__control_group.getActivateControl().getObj()
        obj.resize(h, obj.height())
        obj.setMinimumSize(h, obj.height())
        win = self.__control_group.getActivateControl().getSelf()
        win.resize(win.width(), h + 1)

    def myStatusbar(self):
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.statusbar.addWidget(QLabel("{}".format(self.__control_group.getActivateControl().name()[1])))

        self.statusbar.addWidget(QLabel("W"))
        self.w = QSpinBox()
        self.statusbar.addWidget(self.w)
        self.h = QSpinBox()
        self.statusbar.addWidget(QLabel("H"))
        self.statusbar.addWidget(self.h)

        self.w.setMinimum(1)
        self.h.setMinimum(1)
        self.w.setMaximum(500)
        self.h.setMaximum(500)

        obj = self.__control_group.getActivateControl().getObj()
        self.w.setValue(obj.width())
        self.h.setValue(obj.height())

        self.w.textChanged.connect(self.w_Event)
        self.h.textChanged.connect(self.h_Event)

    def textChanged_Event(self):
        style = self.code_edit.text()
        try:
            obj = self.__control_group.getActivateControl().getObj()
            obj.setStyleSheet(style)
        except Exception as e:
            print(e)

    def myEvent(self):
        self.code_edit.textChanged.connect(self.textChanged_Event)

    def find_Event(self):
        pass

    def save_Event(self):
        print("save")

    # 快捷键
    def myShortcuts(self):
        QShortcut(QKeySequence(self.tr("Ctrl+F")), self, self.find_Event)
        QShortcut(QKeySequence(self.tr("Ctrl+S")), self, self.save_Event)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "QSS编辑器"))

if __name__ == '__main__':
    # a = ControlShell("QPushButton","btn",None)
    # print(a)
    app = QApplication(sys.argv)

    win = QssEdit()
    win.show()

    sys.exit(app.exec_())
    