# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QssEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets

from GuiLib import QSSEdit
from GuiLib import Tree,Tab

class QssEdit(QMainWindow):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)
        self.setupUi()

        self.myEvent()
    
    def setupUi(self):
        self.setObjectName("self")
        self.resize(1346, 737)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        # -- 左侧树 --
        self.createTree()

        # -- 代码编辑器 --
        self.creatTab()

        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter_2)
        self.stackedWidget.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 23))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)

        self.mySplitter()

        QtCore.QMetaObject.connectSlotsByName(self)

    # 创建树
    def createTree(self):
        self.treeWidget = Tree(self.splitter)
        self.treeWidget.setObjectName("treeWidget")

    def creatTab(self):
        self.tabWidget = Tab(self.splitter)
        # self.tabWidget.addTab(QSSEdit(),"default.qss")
        # self.tabWidget.addTab(QSSEdit(),"test.qss")

    # 布局调整
    def mySplitter(self):
        w1 = int(self.width() * 0.65)
        self.splitter_2.setSizes([w1, self.width() - w1])
        self.splitter.setSizes(
            [int(w1 * 0.3), int(w1 * 0.7)]
        )

    # 打开qss文件,进行编辑
    def open_qss(self,file_name:str):
        self.tabWidget.addTab(QSSEdit(),file_name)

    def myEvent(self):
        self.treeWidget.filenameedit.connect(self.open_qss)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("self", "Tab 1"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("self", "Tab 2"))

if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = QssEdit()
    win.show()

    sys.exit(app.exec_())
    